spring:
  application:
    name: mongo_migrate_multids

# Configure both source & target here
data:
  mongodb:
    source:
      uri: mongodb://localhost:27017/eos
    dest:
      uri: mongodb://localhost:27017/eos_metadata_target

logging:
  level:
    root: INFO
