spring:
  application:
    name: mongo-migrate-multids

# Configure both source & target here
data:
  mongodb:
    source:
      uri: mongodb://localhost:27017/eos
    target:
      uri: mongodb://localhost:27017/eos_metadata_target
    self:
      uri: mongodb://localhost:27017/eos_migration

logging:
  level:
    root: INFO
